version: '3.4'

services:

  app:
    command: sh -c "./wait-for postgres:5432 && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py compilemessages && gunicorn  --access-logfile access.log --error-logfile error.log --capture-output --enable-stdio-inheritance quizbot.wsgi -b 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=quizbot.settings.production
      - SECRET_KEY
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
    volumes:
      - static:/static
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro


  celery_worker:
    environment:
      - DJANGO_SETTINGS_MODULE=quizbot.settings.production
      - SECRET_KEY
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  tg_bot:
    environment:
      - DJANGO_SETTINGS_MODULE=quizbot.settings.production
      - SECRET_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nginx:
    container_name: nginx
    command: wait-for app:8000 -- nginx -g "daemon off;"
    depends_on:
      - app
    image: nginx:alpine
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/wait-for:/bin/wait-for
      - static:/var/www/app/static

volumes:
  static:
