# Generated by Django 2.2 on 2020-02-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200205_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employees.Employee')),
                ('tg_id', models.CharField(max_length=300, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=300, verbose_name='Telegram user name')),
                ('first_name', models.CharField(max_length=300, verbose_name='Telegram first name')),
                ('last_name', models.CharField(max_length=300, verbose_name='Telegram last name')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
