# Generated by Django 2.2 on 2020-02-16 23:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200210_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='days_for_poll',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='1', max_length=1), default=['1'], size=None, verbose_name='Days for poll'),
            preserve_default=False,
        ),
    ]
