# Generated by Django 2.2 on 2020-02-25 11:34

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20200225_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='time_for_poll',
            field=models.TimeField(default=datetime.time(11, 34, 30, 270361), verbose_name='Time for poll'),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_for_poll',
            field=models.TimeField(default=datetime.time(11, 34, 30, 270361), verbose_name='Time for poll'),
        ),
        migrations.AlterField(
            model_name='department',
            name='days_for_poll',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default=['1', '2', '3', '4', '5'], max_length=1, verbose_name='Days for poll'), size=None, verbose_name='Days for poll'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='days_for_poll',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default=['1', '2', '3', '4', '5'], max_length=1, verbose_name='Days for poll'), size=None, verbose_name='Days for poll'),
        ),
    ]
