# Generated by Django 2.2 on 2020-02-25 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20200225_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='time_for_poll',
            field=models.TimeField(default=datetime.datetime(2020, 2, 25, 11, 35, 51, 588867, tzinfo=utc), verbose_name='Time for poll'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_for_poll',
            field=models.TimeField(default=datetime.datetime(2020, 2, 25, 11, 35, 51, 588867, tzinfo=utc), verbose_name='Time for poll'),
        ),
    ]
