# Generated by Django 2.2 on 2020-02-26 04:30

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20200225_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='days_for_poll',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_for_poll',
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(default='shaper2010@gmail.com,', max_length=254, verbose_name='Emails for sending'), default=['medvedev@zvezda-sb.ru'], size=None, verbose_name='Emails for sending'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='time_for_poll',
            field=models.TimeField(default=datetime.datetime(2020, 2, 26, 4, 30, 12, 512916, tzinfo=utc), verbose_name='Time for poll'),
        ),
    ]
