# Generated by Django 2.2 on 2020-02-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20200226_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='time_for_poll',
            field=models.TimeField(auto_now=True, verbose_name='Time for poll'),
        ),
    ]
