# Generated by Django 2.2 on 2020-02-11 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200210_1349'),
        ('polls', '0002_auto_20200205_1232'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('choice_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee', verbose_name='Employee')),
                ('questions', models.ManyToManyField(to='polls.Question', verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
    ]
