# Generated by Django 2.2 on 2020-02-11 11:03

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200211_0908'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='poll',
            managers=[
                ('poll_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Is closed?'),
        ),
        migrations.AddField(
            model_name='poll',
            name='date_closed',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 11, 3, 39, 505820), verbose_name='Date closed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AddField(
            model_name='poll',
            name='state',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='State num'),
        ),
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
        ),
    ]
