# Generated by Django 2.2 on 2020-02-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200211_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='max_votes',
            field=models.IntegerField(default=0, verbose_name='Maximum Votes'),
        ),
    ]
